/* Pediatric DeBias AI — dashboard renderer.
 * All content comes from dashboard/data/dashboard.json, generated by dashboard/build_data.py
 * from the executed audit and verified inventories. Nothing here fabricates a number.
 * No external libraries, no CDNs — works offline and on static hosts (Vercel). */
(function () {
  "use strict";

  const $ = (sel) => document.querySelector(sel);
  const el = (tag, props = {}, kids = []) => {
    const n = document.createElement(tag);
    Object.entries(props).forEach(([k, v]) => {
      if (k === "text") n.textContent = v;
      else if (k === "html") n.innerHTML = v;
      else if (k === "class") n.className = v;
      else n.setAttribute(k, v);
    });
    (Array.isArray(kids) ? kids : [kids]).forEach((c) => {
      if (c == null) return;
      n.appendChild(typeof c === "object" && c.nodeType ? c : document.createTextNode(String(c)));
    });
    return n;
  };
  const pct = (x) => `${Number(x).toFixed(1)}%`;

  function showError(msg) {
    const b = $("#error-banner");
    b.textContent = msg;
    b.hidden = false;
  }

  /* ---------- status cards ---------- */
  function renderStatus(d) {
    const cards = [
      { k: "Project phase", v: `Phase ${d.project.phase}`, s: "of planned phases", cls: "ok" },
      { k: "Audit verdict", v: d.audit.verdict.replace(" (conditional)", ""), s: "conditional — see audit", cls: "ok" },
      { k: "Patients", v: d.audit.dimensions.n_rows, s: `${d.audit.dimensions.n_cols} columns · 0 duplicates`, cls: "info" },
      { k: "Models trained", v: 0, s: "training gated on audit", cls: "warn" },
      { k: "Experiments run", v: 0, s: "metrics stay empty until then", cls: "warn" },
      { k: "Verified papers", v: d.literature.count, s: `${d.literature.categories.length} categories · DOI-checked`, cls: "info" },
    ];
    const host = $("#status-cards");
    host.innerHTML = "";
    cards.forEach((c) =>
      host.appendChild(
        el("div", { class: "card" }, [
          el("div", { class: "k", text: c.k }),
          el("div", { class: `v ${c.cls}`, text: String(c.v) }),
          el("div", { class: "s", text: c.s }),
        ])
      )
    );
    $("#phase-badge").textContent = d.project.status;
  }

  /* ---------- audit ---------- */
  function renderAudit(a) {
    $("#audit-verdict").textContent = a.verdict;
    $("#audit-meta").textContent =
      `${a.sources.audited_file} · ${a.sources.license} · DOI ${a.sources.zenodo_doi} · ` +
      `${a.missing_cells_total.toLocaleString()} missing cells (${a.missing_cells_pct}%) · audited ${a.timestamp}`;

    // class balance
    const cb = a.class_balance;
    const cbHost = $("#class-balance");
    cbHost.innerHTML = "";
    [
      { label: "appendicitis", n: cb.n_positive, alt: false },
      { label: "no appendicitis", n: cb.n_negative, alt: true },
    ].forEach((r) => {
      const width = (r.n / (cb.n_positive + cb.n_negative)) * 100;
      cbHost.appendChild(
        el("div", { class: "bar-row" }, [
          el("span", { text: r.label }),
          el("div", { class: "bar-track" }, el("div", { class: `bar-fill${r.alt ? " alt" : ""}`, style: `width:${width.toFixed(1)}%` })),
          el("span", { class: "bar-val", text: `${r.n} (${width.toFixed(1)}%)` }),
        ])
      );
    });

    // age bins
    const ageHost = $("#age-dist");
    ageHost.innerHTML = "";
    const bins = a.age.age_bins;
    const maxAge = Math.max(...Object.values(bins), 1);
    Object.entries(bins).forEach(([label, n]) => {
      ageHost.appendChild(
        el("div", { class: "bar-row" }, [
          el("span", { text: label }),
          el("div", { class: "bar-track" }, el("div", { class: "bar-fill", style: `width:${((n / maxAge) * 100).toFixed(1)}%` })),
          el("span", { class: "bar-val", text: String(n) }),
        ])
      );
    });

    // missingness
    const missHost = $("#missingness");
    missHost.innerHTML = "";
    a.missingness_top.forEach((m) => {
      missHost.appendChild(
        el("div", { class: "bar-row" }, [
          el("span", { text: m.column }),
          el("div", { class: "bar-track" }, el("div", { class: "bar-fill miss", style: `width:${m.pct_missing.toFixed(1)}%` })),
          el("span", { class: "bar-val", text: `${m.pct_missing.toFixed(1)}%` }),
        ])
      );
    });

    // flags table
    const tb = $("#flags-table tbody");
    tb.innerHTML = "";
    Object.entries(a.flagged_columns).forEach(([col, info]) => {
      tb.appendChild(
        el("tr", {}, [
          el("td", {}, el("code", { text: col })),
          el("td", { text: info.univariate_auc_max == null ? "—" : info.univariate_auc_max.toFixed(4) }),
          el("td", {}, info.flags.map((f) => el("span", { class: `flag${f.startsWith("HIGH") ? " pos" : ""}`, text: f }))),
        ])
      );
    });

    // anchor facts
    const anchorHost = $("#anchor-facts");
    anchorHost.innerHTML = "";
    [
      `Missing values: ${a.anchor.n_missing}`,
      `Agreement with final diagnosis (2-class anchors): ${pct(a.anchor.presumptive_vs_final_diagnosis_agreement * 100)}`,
      `Estimated incorrect-anchor rate: ${a.anchor.incorrect_anchor_rate_pct}%`,
      `Collapsed: ${Object.entries(a.anchor.collapsed_distribution).map(([k, v]) => `${k}=${v}`).join(", ")}`,
    ].forEach((t) => anchorHost.appendChild(el("li", { html: t.replace(/: ([\d.]+%?|[\d,]+)$/, ': <span class="num">$1</span>') })));

    // targets
    const tHost = $("#targets");
    tHost.innerHTML = "";
    Object.entries(a.targets).forEach(([name, dist]) => {
      const li = el("li");
      li.appendChild(el("strong", { text: name + ": " }));
      li.appendChild(el("span", { text: Object.entries(dist).map(([k, v]) => `${k} = ${v.n} (${v.pct}%)`).join(" · ") }));
      tHost.appendChild(li);
    });

    // limitations
    const lHost = $("#audit-limits");
    lHost.innerHTML = "";
    a.limitations.forEach((t) => lHost.appendChild(el("li", { text: t })));
  }

  /* ---------- datasets ---------- */
  function renderDatasets(rows) {
    const tb = $("#datasets-table tbody");
    tb.innerHTML = "";
    rows.forEach((r) => {
      tb.appendChild(
        el("tr", {}, [
          el("td", {}, el("strong", { text: r.Dataset })),
          el("td", { text: r.Source }),
          el("td", {}, el("code", { text: r.DOI })),
          el("td", { text: r.N }),
          el("td", { text: r.License }),
          el("td", { text: (r.Role.match(/Phase [A-C]/) || ["—"])[0] }),
          el("td", { text: r.Role }),
        ])
      );
    });
  }

  /* ---------- pipeline ---------- */
  function renderPipeline(p) {
    const sHost = $("#stages");
    sHost.innerHTML = "";
    p.stages.forEach((s) => {
      const vis =
        s.sees_prediction === true ? "sees prediction"
        : s.sees_prediction === false ? "prediction-blind"
        : String(s.sees_prediction);
      sHost.appendChild(
        el("li", {}, [
          el("div", { class: "st-n", text: `Stage ${s.n}` }),
          el("div", { class: "st-name", text: s.name }),
          el("div", { class: "st-purpose", text: s.purpose }),
          el("span", { class: `st-vis ${s.sees_prediction === true ? "yes" : "no"}`, text: `visibility: ${vis}` }),
        ])
      );
    });

    const cHost = $("#conditions");
    cHost.innerHTML = "";
    p.conditions.forEach((c) => {
      cHost.appendChild(el("li", { html: `<strong>${c.name}</strong> <span>— anchor: ${c.anchor}</span>` }));
    });

    const aHost = $("#ablations");
    aHost.innerHTML = "";
    p.ablations.forEach((a) => {
      aHost.appendChild(el("li", { html: `#${a.id} ${a.name} <span class="pill plan">${a.status}</span>` }));
    });
  }

  /* ---------- agents ---------- */
  function renderAgents(agents) {
    const host = $("#agents");
    host.innerHTML = "";
    agents.forEach((a) =>
      host.appendChild(
        el("div", { class: "agent" }, [
          el("div", { class: "aid", text: a.id }),
          el("div", { class: "aname", text: a.name }),
          el("div", { class: "asees", html: `<b>Sees:</b> ${a.sees}` }),
          el("div", { class: "aout", html: `<b>Output:</b> ${a.output}` }),
          el("div", { class: "arule", text: a.rule }),
        ])
      )
    );
  }

  /* ---------- metrics ---------- */
  function renderMetrics(metrics) {
    const tb = $("#metrics-table tbody");
    tb.innerHTML = "";
    metrics.forEach((m) => {
      tb.appendChild(
        el("tr", {}, [
          el("td", {}, el("code", { text: m.code })),
          el("td", { text: m.name }),
          el("td", { text: m.formula }),
          el("td", {}, el("span", { class: "pill plan", text: "pending experiment" })),
        ])
      );
    });
  }

  /* ---------- literature ---------- */
  function renderLiterature(lit) {
    $("#lit-count").textContent = `${lit.count} verified entries`;
    let activeCat = "All";
    const search = $("#lit-search");

    const chipHost = $("#lit-chips");
    chipHost.innerHTML = "";
    ["All", ...lit.categories].forEach((c) => {
      const chip = el("button", { class: `chip${c === "All" ? " active" : ""}`, type: "button", text: c });
      chip.addEventListener("click", () => {
        activeCat = c;
        chipHost.querySelectorAll(".chip").forEach((x) => x.classList.remove("active"));
        chip.classList.add("active");
        draw();
      });
      chipHost.appendChild(chip);
    });

    const listHost = $("#lit-list");
    function draw() {
      const q = (search.value || "").trim().toLowerCase();
      listHost.innerHTML = "";
      const rows = lit.entries.filter((e) => {
        const inCat = activeCat === "All" || e.category === activeCat;
        const inQ = !q || `${e.title} ${e.authors} ${e.venue} ${e.year}`.toLowerCase().includes(q);
        return inCat && inQ;
      });
      if (!rows.length) {
        listHost.appendChild(el("div", { class: "lit-empty", text: "No entries match this filter." }));
        return;
      }
      rows.forEach((e) => {
        listHost.appendChild(
          el("div", { class: "lit-item" }, [
            el("div", { class: "lt", text: e.title }),
            el("div", { class: "lm", text: `${e.authors.split(";").slice(0, 3).join("; ")}${e.authors.split(";").length > 3 ? " et al." : ""} · ${e.year} · ${e.venue}` }),
            el("div", { class: "lm", text: e.relevance }),
            el("div", {}, [
              el("span", { class: "lc", text: e.category }),
              " ",
              el("a", { href: e.url, target: "_blank", rel: "noopener noreferrer", text: e.doi.startsWith("10.") ? `doi:${e.doi}` : e.url.replace(/^https?:\/\//, "").slice(0, 40) }),
            ]),
          ])
        );
      });
    }
    search.addEventListener("input", draw);
    draw();
  }

  /* ---------- docs ---------- */
  function renderDocs(docs) {
    const host = $("#doc-links");
    host.innerHTML = "";
    docs.forEach((d) =>
      host.appendChild(el("a", { href: d.path, target: "_blank", rel: "noopener" }, [
        el("span", { text: d.label }),
        el("span", { class: "p", text: d.path }),
      ]))
    );
  }

  /* ---------- boot ---------- */
  fetch("data/dashboard.json", { cache: "no-store" })
    .then((r) => {
      if (!r.ok) throw new Error(`dashboard.json: HTTP ${r.status}`);
      return r.json();
    })
    .then((d) => {
      renderStatus(d);
      renderAudit(d.audit);
      renderDatasets(d.datasets);
      renderPipeline(d.pipeline);
      renderAgents(d.agents);
      renderMetrics(d.bias_metrics);
      renderLiterature(d.literature);
      renderDocs(d.docs);
      $("#generated-at").textContent = `dashboard data generated ${d.generated_utc} · dashboard/v1`;
      document.title = `Pediatric DeBias AI — ${d.project.status}`;
    })
    .catch((err) => {
      showError(`Failed to load dashboard data (${err.message}). Rebuild with: python dashboard/build_data.py`);
      $("#phase-badge").textContent = "data missing";
    });
})();
